### ISSUE TITLE
Filtrer les  permaliens

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#1]
Un permalien "classique"  généré  par  l'application  est  du  type :

https://geofoncier.brgm-rec.fr/index.php?echelle=1128&centre=121486,5481503&context=metropole&layers=metropole:aurige,RFU_FXX,ADMINISTRATIVEUNITS.BOUNDARIES,GEOGRAPHICALGRIDSYSTEMS.MAPS,CADASTRALPARCELS.PARCELS,ORTHOIMAGERY.ORTHOPHOTOS,ORTHOIMAGERY.ORTHOPHOTOS2000-2005

Or il  faut necessairement un lien du  type :
https://pro.geofoncier.fr/index.php?echelle=1128&centre=121486,5481503&context=metropole

Il  fautdrait  accepter  tout  type  de  permalien pouvu qu'il y ait  les  paramètres  édéquats.
Par ailleurs le  message  "Le permalien est  invalide"  meriterait  d'être  plus  explicite  (Quels  sont  le/les param(s) manquant(s) ?

**Comment by m431m** [comment]
Corrigé (0b168e1d8ece578b3a7cd59a3b5552d1a3dbca42)

Je laisse en suspens la deuxième partie du ticket pour le moment. 
Qu'entends-tu par "tout type de permalien" ? Peux-tu donner un exemple ?

**Comment by SOGEFI** [comment]
exemple : 
https://pro.geofoncier.fr/index.php?echelle=1128&centre=121486,5481503&context=metropole&chose=truc

devrait marcher  car  tout ce  qu'il  faut  y est  or  actuellement  ça  ne  marche pas.

**Comment by m431m** [comment]
Ok ça marche avec le commit 0b168e1
