### ISSUE TITLE
Impossible de changer d'utilisateur

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#10]
Dès lors que les idenfiant de connection ont été saisie, il est impossible d'en changer, même en fermant puis ré-ouvrant QGIS.

**Comment by m431m** [comment]
Effectivement, si l'on coche l'option "se souvenir de moi"...

**Comment by m431m** [comment]
Je viens de re-vérifier avec la version 2.10.1, tu peux changer les identifiants même si tu coche l'option 'se souvenir de moi'. Normalement, dès que tu fermes QGIS, le téléchargement de données nécessite une reconnection au serveur donc de valider les identifiants à nouveau.
