### ISSUE TITLE
Suppression de plusieurs objets à la fois impossible

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#11]
zone : https://geofoncier.brgm-rec.fr/index.php?echelle=2257&centre=15008,5850701&context=metropole

en une seule fois on tente de supprimer : 
N 32458
N 32454
L30192
L30198
L30186
L30182
en tant que GE 04593

et on y arrive pas.

**Comment by m431m** [comment]
Tu obtiens un message d'erreur ?

**Comment by SOGEFI** [comment]
non, rien

**Comment by m431m** [comment]
Le problème vient du signal : 
**committedFeaturesRemoved(const QString &, const [[QgsFeatureIds]] & )"** 
Ce qui m'étonne beaucoup car il me semblait bien que cela fonctionnait correctement avant l'été... 
J'ai constaté une erreur C++ (80879f5) depuis les dernières version de QGIS ou dernière mise à jour d'OSX 10.10 (ou les deux). Tu n'as rien constaté sur Win ?
Bref, le commit 80879f5 corrige l'erreur, mais le signal n'a aucun effet, et je ne récupère plus les features supprimés... je cherche.

**Comment by m431m** [comment]
Sous QGIS 2.8.2, cela fonctionne très bien...

**Comment by m431m** [comment]
L'API n'a pas changé, s'agirait-il d'une régression ?
http://qgis.org/api/2.10/classQgsVectorLayer.html#a520550b45603ed20d593b1050768bd97

**Comment by m431m** [comment]
Pour tester :
Ajouter un layer ; le selectionner ; passer en mode édition
Ajouter dans la console python :

```
>>> layer=iface.activeLayer()
>>> def listener(s,l):
>>>    print s,l
>>> layer.committedFeaturesRemoved.connect(listener)
```

Puis supprimer des objets et quitter le mode édition.
