### ISSUE TITLE
identification de api_dossier et affcetation au changeset manquant

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#12]
Au moment de la création d'un changeset il faut demande à l'utilisateur une référence dossier (enr_cab_createur + enr_ref_dosiser) qui sert à identifer enr_api (via service B5).
La valeru de enr_api sert à renseigner api_dossier pour la création d'un changeset.

**Comment by m431m** [comment]
Ceci ?

Open ChangeSet
https://github.com/neogeo-technologies/GeofoncierEditeurRFU/blob/master/rfu_connector.py#L445
=> https://github.com/neogeo-technologies/GeofoncierEditeurRFU/blob/master/client.py#L59

Close ChangeSet
https://github.com/neogeo-technologies/GeofoncierEditeurRFU/blob/master/rfu_connector.py#L481
=> https://github.com/neogeo-technologies/GeofoncierEditeurRFU/blob/master/client.py#L69

Si oui, c'est déjà le fonctionnement normal.

**Comment by m431m** [comment]
Ok, je viens de voir ce point avec Matthieu et effectivement ça n'est pas implémenté dans le plugin.
