### ISSUE TITLE
Les couches sommets et limites doivent être éditables dès leur chargement 

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#2]
Les couches sommets et limites doivent être éditables dès leur chargement (actuellement il faut  les  basculer  en déditable manuellement).

idée : si  la  clé  logiciel  ne  permet  pas  d'agir  en modification alors il  doit  être  impossible  de  passer  les  couches  en  éditables.

**Comment by m431m** [comment]
> Les couches sommets et limites doivent être éditables dès leur chargement (actuellement il faut les basculer en déditable manuellement).

Pas de problème.

> idée : si la clé logiciel ne permet pas d'agir en modification alors il doit être impossible de passer les couches en éditables.

C'est le comportement normal, mais nous allons tout de même nous en assurer avec @mlefort.

**Comment by m431m** [comment]
Corrigé (b0cd3651c9c8ca1b2838926b920a3ca3eebc066a)

**Comment by m431m** [comment]
Re-corrigé (74c016e3a8aa0fb2495640508f4a810f66d16242)
