### ISSUE TITLE
uniformiser  la  création  des objets

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#3]
Bizarerie  ergonomique : 
la creation  d'un  sommet  ce  fait depuis  une  fenêtre  alors que  la  création d'une limite  ce  fait  depuis le  panneau.

à uniformaiser  dans  le panneau ?

**Comment by m431m** [comment]
Oui le panneau correspond au "connecteur" tandis que les outils d'édition sont à part puisque leur fonction respective est différente. Il est plus logique, je trouve, de les séparer. A discuter.

**Comment by m431m** [comment]
Oui car le panneau permet l'interaction avec l'interface principale (nécessaire pour la création d'une limite puisque l'utilisateur peut cliquer sur la carte) tandis que la fenêtre ne le permet pas (ce qui oblige l'utilisateur à valider la création d'un point). C'est un peu déroutant mais je n'ai pas trouvé mieux...
