### ISSUE TITLE
boutons plus explicites

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#4]
pour  les  bouton  "télécharger" et "envoyer" il  faudrait  des  icone  plus  explicite.

Par ailleurs  il serait  souhaitable  que les boutons  "nouveau sommet" et "nouvelle limite"  soient  dans  le  panneau.

**Comment by m431m** [comment]
> pour les bouton "télécharger" et "envoyer" il faudrait des icone plus explicite.

:+1:

**Comment by m431m** [comment]
C'est fait (abf63423d704109f98c94b9ae6d68f197ae93122)
