### ISSUE TITLE
problème de  couleur  sur  les  limites

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#6]
1 . on  ajoute  une  limite appuyée  sur  deux point  existant
2. on clique  sur  envoyé
3.  on annule
4. la limite passe  en bleu  foncé alors  qu'elle  ne le devrait pas

**Comment by m431m** [comment]
> la limite passe en bleu foncé alors qu'elle ne le devrait pas

 Oui, on quitte le mode 'édition' alors que l'on ne devrait pas. Je vais corriger cela.

**Comment by m431m** [comment]
> > la limite passe en bleu foncé alors qu'elle ne le devrait pas
> 
> Oui, on quitte le mode 'édition' alors que l'on ne devrait pas. Je vais corriger cela.

Je reviens sur ce que j'ai dit. Voici le fonctionnement normal du plugin (suivant la logique QGis) : on ne peut exporter les données tant que celles-ci ne sont pas enregistrées (c-à-d fermer le mode ‘édition’ et valider les modifications).

Dans la version actuelle du code, pour simplifier, j'ai autorisé la publication des données même lorsque l'utilisateur est en mode édition. C'est pour cela que l'application bascule automatiquement d'un mode à l'autre au moment où l'on clique sur ‘envoyer’. Impossible de revenir en arrière donc une fois les modifications validées. Il serait surement préférable d'interdire l'action en mode ‘édition’.
