### ISSUE TITLE
Limite  de  la  zone  extraite invisibles

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#7]
Il  me  semble  dengeraux  de   ne  pas  indiquer  à  l'utilisateur  les  limites  de  la  zone  extraite car potentiellement  il  pourrait  créer  des  nouveau  objets  là  où il  y en  a  déjà  (il  ne  les voit  pas).

Je  verai  bien  un  couche  "zone  de  travaille" avec  un  polygone  qui  inque  en pontillée  la  BBOX  extraite et tant que  l'on  y ait, le  nom  de  la couche serait du type  : "Zone de travail extraite le 16/06/2015 11h06 par  Martin DUJALON".

**Comment by m431m** [comment]
Mais ça n'empêchera pas à l'utilisateur de faire "n'importe quoi"...
On pourrait mettre en suspens cette demande d'évolution ? Je préfère que l'on valide déjà le bon fonctionnement du plugin avant d'ajouter de nouvelles fonctionnalités. On retient l'idée et on revient dessus plus tard ?
