### ISSUE TITLE
interdire la  création  de  limites  absurdes

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#8]
Actuellement rie  n'empêche  de  créer une  limite  reprenant  les  points  d'une  limite existante.

**Comment by m431m** [comment]
Non effectivement, mais est-ce si incohérent ? Normalement, n'est pas l'API qui vérifie si les objets sont en doublon et dans ce cas rejette la modification ? 
Ça me parait plus délicat d'interdire la création d'objet côté QGis... à discuter...
