### ISSUE TITLE
Projection  de  visualisation inapropriée

### ISSUE THREAD

**Issue by SOGEFI** [neogeo-technologies/geofoncier-editeur-rfu-qgis#9]
Le  choix  de  la  projection  plane  (dans la  liste  du panneau) devrait  permettre de forcer  la  projection  d'affichage (à  la  volée)  de  QGIS.

Les  GE  travaillent  toujours  en CC et afficher le RFU  en coordonnées  géo  n'a pas  de  sens...

**Comment by m431m** [comment]
> Les GE travaillent toujours en CC et afficher le RFU en coordonnées géo n'a pas de sens...

Les objets sont chargés dans le système de coordonnées défini pour le projet QGis courant, qui n'est pas forcement le WGS84 (certes la configuration par défaut de QGis). Forcer la projection au moment du chargement ne me parait pas être une bonne idée car si l'utilisateur travaille dans un environnement particulier (avec des fonds de cartes WMS par exemple) cela risque de chambouler son projet...

**Comment by m431m** [comment]
Fait -> 1f4c9e042908307240c206fa3569dccbb3feda81
